name: Test

on:
  push:
  pull_request:

env:
  JAVA_DIST: 'zulu'
  JAVA_VERSION: 22

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Compile and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Build and Test
        run: |
          export MAVEN_OPTS="-Xms512m -XX:+UseG1GC -XX:+PrintGCDetails -XX:+HeapDumpOnOutOfMemoryError -XX:+UseCompressedOops"
          echo "Using MAVEN_OPTS: $MAVEN_OPTS"
          xvfb-run mvn -B verify -Djavafx.platform=linux jacoco:report -Pcoverage || { echo "Maven build failed"; exit 1; }
          echo "Maven build completed successfully"
          xvfb-run mvn -B verify -Djavafx.platform=linux jacoco:report -Pcoverage
          unset MAVEN_OPTS
      - name: Get JaCoCo Coverage
        id: coverage
        run: |
          coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
          echo "COVERAGE=$coverage" >> $GITHUB_ENV

      - name: Fail if coverage has not improved.
        run: |
          coverage=$COVERAGE
          threshold=13.43
          if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
            echo "Coverage has not improved."
            exit 1
          else
            echo "New coverage: $coverage%"
          fi
